# Generated by Django 4.2.20 on 2025-03-15 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите наименование задачи', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='опишите задачу', null=True, verbose_name='описание')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('status', models.CharField(choices=[('active', 'активная'), ('accept', 'взята на исполнение'), ('complete', 'выполнена'), ('cancel', 'отклонена')], default='active', max_length=10, verbose_name='статус задачи')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Укажите связанную задачу', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task', verbose_name='Связанная задача')),
            ],
        ),
    ]
