# Generated by Django 4.2.20 on 2025-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Признак важности задачи'),
        ),
    ]
